// Si quieres agregar una nueva tabla para generar, agrégala aquí
// No olvides usar mayúsculas.
// No elimines tablas existentes a menos que estés seguro de que ya no se necesitan.
// Esta lista es utilizada por el generador de entidades para Oracle.
// Una vez generada la entidad, copiar la carpeta libs\database\src\generator\entities\oracle a la ubicación correspondiente => libs\database\src\entities\autogenerated, eliminando la carpeta actual libs\database\src\entities\autogenerated\oracle

export const OracleTablesToGenerate = [
  'PERSONAL',
  'ESPECIALIDAD_PERSONAL',
  'AREAS',
  'SSA_PUESTOS_TRABAJO',
  'COMPANIAS',
  'PARROQUIAS',
  'CANTONES',
  'PROVINCIAS',
  'SSA_CLASIFICACION_OCUPACIONES',
  'SSA_PUESTOS_SUT',
  'SGI_ISODIVISION',
  'SGI_ISODPTO',
  'SGI_ISOAREAS',
  'SGI_ISOCARGO',
  'DEPARTAMENTOS',
  'NOM_ORG_COORDINACION',
  'NOM_ORG_DIRECCION',
  'SGI_ISOORGANIGRAMA',
  'SGI_ISONODO_ORG',
  'ESPECIALIDADES_MEDICOS',
  'ESPECIALIDADES',
  'HORARIOS_MEDICO',
  'ADM_SERVIDORES_DIAGNOSTICO',
  'ADM_GRUPO_DIAGNOSTICO',
];
