### Availability
@host = http://localhost:3000
@specialtyId = CRD
@providerId = M918

@dateFrom = 2026-01-01

@dateTo = 2026-01-31

### getSpecialties
GET {{host}}/v1/scheduling/availability/specialties

### getProvidersBySpecialty
GET {{host}}/v1/scheduling/availability/specialties/{{specialtyId}}/providers

### getProviderDates
GET {{host}}/v1/scheduling/availability/providers/{{providerId}}/dates

### getProviderDatesByDateRange
GET {{host}}/v1/scheduling/availability/providers/{{providerId}}/dates?dateFrom={{dateFrom}}&dateTo={{dateTo}}