export * from './adm-template-dto.map';
export * from './auto-admision-template.dto';
export * from './bienvenida-template.dto';
export * from './citas-turno-template.dto';
export * from './documento-derivacion-aprovado-template.dto';
export * from './documento-derivacion-pendiente-template.dto';
export * from './documento-derivacion-rechazado-template.dto';
export * from './reagendamiento-template.dto';
export * from './recordatorio-cita-template.dto';
