import { isEntity } from '../../common/utils';
import * as autogeneratedEntities from '../../entities/autogenerated/oracle';
import { DatabaseAllEntities } from '../all/database-all.entities';

export const databaseOracleOwnEntities = [...DatabaseAllEntities].filter(
  isEntity,
);

export const databaseOracleEntities = [
  ...databaseOracleOwnEntities,
  ...Object.values(autogeneratedEntities),
].filter(isEntity);
