name: hsm-app

networks:
  hsm-app-network:
    name: hsm-app-network
    driver: bridge

volumes:
  db_postgres_data:
    name: hsm-app-db_postgres-data
  db_redis_data:
    name: hsm-app-db_redis-data
  db_minio_data:
    name: hsm-app-db_minio-data

services:
  api:
    image: hsm-app-be-api
    build:
      context: ../
      dockerfile: apps/backend/api/Dockerfile
      target: dev
    networks:
      - hsm-app-network
    ports:
      - 10001:3000
    volumes:
      - ../:/app
      - /app/node_modules
    env_file:
      - ../.env
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - minio
      - worker

  worker:
    image: hsm-app-be-worker
    build:
      context: ../
      dockerfile: apps/backend/worker/Dockerfile
      target: dev
    networks:
      - hsm-app-network
    ports:
      - 10002:3001
    volumes:
      - ../:/app
      - /app/node_modules
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
      - minio
    restart: unless-stopped

  postgres:
    image: postgres:18-bookworm
    networks:
      - hsm-app-network
    ports:
      - 10003:5432
    volumes:
      - db_postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hsm
    restart: unless-stopped

  redis:
    image: redis:8-bookworm
    networks:
      - hsm-app-network
    ports:
      - 10004:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/users.acl:/usr/local/etc/redis/users.acl:ro
      - db_redis_data:/data
    environment:
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    command: [redis-server, /usr/local/etc/redis/redis.conf]
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    networks:
      - hsm-app-network
    ports:
      - 10005:9000
      - 10006:9001
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    volumes:
      - db_minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped