
FROM node:24-bookworm-slim
ARG  APP_TYPE

WORKDIR /app
RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

COPY . .

RUN pnpm build:$APP_TYPE
ENV APP_TYPE=${APP_TYPE}
CMD ["sh","-lc","pnpm start:${APP_TYPE}:prod"]
