export interface OracleEntityHbsData {
  owner: string;
  tableName: string;
  tableNameTS: string;
  importsTS?: string[];
  columns: {
    columnName: string;
    columnNameTS: string;
    columnId?: number;
    dataType?: string;
    dataLength?: number;
    dataPrecision?: number;
    dataScale?: number;
    dataDefault?: string;
    comment?: string;
    dataTypeTS?: string;
    nullable?: boolean;
  }[];
  constraints?: {
    primary?: {
      constraintName: string;
      columns: { columnName: string; isAutoGenerated: boolean }[];
    };
    foreign?: {
      constraintName: string;
      relationNameTS: string;
      relationTypeTS: 'many-to-one' | 'one-to-many' | 'one-to-one';
      columns: {
        columnName: string;
        columnNameTS: string;
        referencedTableName: string;
        referencedTableNameTS: string;
        referencedColumnName: string;
        referencedColumnNameTS: string;
      }[];
    }[];
    unique?: { constraintName: string; columnNames: string[] }[];
  };
  indexes?: { indexName: string; columnNames: string[]; isUnique: boolean }[];
}
