export * from './auto-admision.template';
export * from './bienvenida.template';
export * from './citas-turno.template';
export * from './documento-derivacion-aprovado.template';
export * from './documento-derivacion-pendiente.template';
export * from './documento-derivacion-rechazado.template';
export * from './reagendamiento.template';
export * from './recordatorio-cita.template';
export * from './registry';
