from node:24-bookworm

WORKDIR /app
RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile --prod

COPY . .

RUN pnpm build:worker

CMD ["pnpm", "start:worker:prod"]