import { isEntity } from '../../common/utils';
import * as autogeneratedEntities from '../../entities/autogenerated/oracle';
import { databaseUniversalEntities } from '../database-universal.entities';

export const databaseOracleEntities = [
  ...databaseUniversalEntities,
  ...Object.values(autogeneratedEntities),
].filter(isEntity);
