import { isEntity } from '../../common/utils';
import * as autogeneratedEntities from '../../entities/autogenerated/oracle';
import { databaseUniversalEntities } from '../database-universal.entities';

export const databaseOracleOwnEntities = [...databaseUniversalEntities].filter(
  isEntity,
);

export const databaseOracleEntities = [
  ...databaseOracleOwnEntities,
  ...Object.values(autogeneratedEntities),
].filter(isEntity);
