name: Deploy

on:
  workflow_call:
    inputs:
      APP_TYPE:
        description: Type of application to deploy (main or worker)
        required: true
        type: string
      NAMESPACE:
        description: Kubernetes namespace to deploy to
        required: true
        type: string
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: kubectl rollout restart
        run: |
          echo kubectl rollout restart deployment hsm-app-be-${{ inputs.APP_TYPE }} -n ${{inputs.NAMESPACE}}
